### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by tonyyyye** [golbin/WaveNet#2]
We tried to run train.py, but there were errors as below:

> python3 train.py --data_dir="./test/data" --output_dir="./outputs"
> THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
> Traceback (most recent call last):
>   File "train.py", line 59, in <module>
>     trainer = Trainer(args)
>   File "train.py", line 17, in __init__
>     lr=args.lr)
> ...
> ...
>     return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
> RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66
> 

I don't know why.

**Comment by golbin** [comment]
Make your model smaller with options like layer_size, stack_size like that.

Options in wavenet/config.py

**Comment by tonyyyye** [comment]
OK, i will try. Thanks.

**Comment by golbin** [comment]
This WaveNet implementation is not tested well.

So it’s better you use other model if you want to use right now.
